spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.101:3306/mybatisplus_demo?charsetEncoding=utf-8&serverTimeZone=Asia/Shanghai
    username: root
    password: ltr20001121


logging:
  level:
    com.seamew: DEBUG

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: idDelete
      logic-delete-value: 1
      logic-not-delete-value: 0